-- CreateTable
CREATE TABLE `StudentProfile` (
    `id` VARCHAR(191) NOT NULL,
    `studentName` VARCHAR(191) NOT NULL,
    `enrollmentNo` VARCHAR(191) NOT NULL,
    `gender` VARCHAR(191) NOT NULL,
    `branch` VARCHAR(191) NOT NULL,
    `birthdate` DATETIME(3) NOT NULL,
    `age` INTEGER NOT NULL,
    `passingYearSSC` INTEGER NOT NULL,
    `percentageSSC` DOUBLE NOT NULL,
    `passingYearHSC` INTEGER NULL,
    `percentageHSC` DOUBLE NULL,
    `passingYearD2D` INTEGER NULL,
    `percentageD2D` DOUBLE NULL,
    `studyGap` VARCHAR(191) NULL,
    `mediumSchool` VARCHAR(191) NOT NULL,
    `spiSem1` DOUBLE NULL,
    `spiSem2` DOUBLE NULL,
    `spiSem3` DOUBLE NULL,
    `spiSem4` DOUBLE NULL,
    `spiSem5` DOUBLE NULL,
    `currentCGPA` DOUBLE NOT NULL,
    `percentageBE` DOUBLE NOT NULL,
    `totalBacklogs` INTEGER NOT NULL,
    `backlogTitles` VARCHAR(191) NULL,
    `currentBacklogs` INTEGER NOT NULL,
    `currentBacklogTitles` VARCHAR(191) NULL,
    `mobileNumber` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `address` VARCHAR(191) NOT NULL,
    `city` VARCHAR(191) NOT NULL,
    `pincode` VARCHAR(191) NOT NULL,
    `district` VARCHAR(191) NOT NULL,
    `file` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `StudentProfile_enrollmentNo_key`(`enrollmentNo`),
    UNIQUE INDEX `StudentProfile_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
